import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Title_3d(props) {
  const { nodes, materials } = useGLTF('/models/main-title.glb')
  return (
    <group receiveShadow {...props} dispose={null} scale={0.0015} position={[0,0,5]} castShadow>
      <mesh
        
        name="Loft19"
        castShadow
        receiveShadow
        geometry={nodes.Loft19.geometry}
        material={nodes.Loft19.material}
      />
      <mesh
        name="Loft18"
        castShadow
        receiveShadow
        geometry={nodes.Loft18.geometry}
        material={nodes.Loft18.material}
      />
      <mesh
        name="Loft17"
        castShadow
        receiveShadow
        geometry={nodes.Loft17.geometry}
        material={nodes.Loft17.material}
      />
      <mesh
        name="Loft16"
        castShadow
        receiveShadow
        geometry={nodes.Loft16.geometry}
        material={nodes.Loft16.material}
      />
      <mesh
        name="Loft15"
        castShadow
        receiveShadow
        geometry={nodes.Loft15.geometry}
        material={nodes.Loft15.material}
      />
      <mesh
        name="Loft14"
        castShadow
        receiveShadow
        geometry={nodes.Loft14.geometry}
        material={nodes.Loft14.material}
      />
      <mesh
        name="Loft13"
        castShadow
        receiveShadow
        geometry={nodes.Loft13.geometry}
        material={nodes.Loft13.material}
      />
      <mesh
        name="Loft12"
        castShadow
        receiveShadow
        geometry={nodes.Loft12.geometry}
        material={nodes.Loft12.material}
      />
      <mesh
        name="Loft11"
        castShadow
        receiveShadow
        geometry={nodes.Loft11.geometry}
        material={nodes.Loft11.material}
      />
      <mesh
        name="Loft10"
        castShadow
        receiveShadow
        geometry={nodes.Loft10.geometry}
        material={nodes.Loft10.material}
      />
      <mesh
        name="Loft9"
        castShadow
        receiveShadow
        geometry={nodes.Loft9.geometry}
        material={nodes.Loft9.material}
      />
      <mesh
        name="Loft8"
        castShadow
        receiveShadow
        geometry={nodes.Loft8.geometry}
        material={nodes.Loft8.material}
      />
      <mesh
        name="Loft7"
        castShadow
        receiveShadow
        geometry={nodes.Loft7.geometry}
        material={nodes.Loft7.material}
      />
      <mesh
        name="Loft6"
        castShadow
        receiveShadow
        geometry={nodes.Loft6.geometry}
        material={nodes.Loft6.material}
      />
      <mesh
        name="Loft5"
        castShadow
        receiveShadow
        geometry={nodes.Loft5.geometry}
        material={nodes.Loft5.material}
      />
      <mesh
        name="Loft4"
        castShadow
        receiveShadow
        geometry={nodes.Loft4.geometry}
        material={nodes.Loft4.material}
      />
      <mesh
        name="Loft3"
        castShadow
        receiveShadow
        geometry={nodes.Loft3.geometry}
        material={nodes.Loft3.material}
      />
      <mesh
        name="Loft2"
        castShadow
        receiveShadow
        geometry={nodes.Loft2.geometry}
        material={nodes.Loft2.material}
      />
      <mesh
        name="Loft1"
        castShadow
        receiveShadow
        geometry={nodes.Loft1.geometry}
        material={nodes.Loft1.material}
      />
    </group>
  )
}

useGLTF.preload('/main-title.glb')